# Generated by Django 3.0.5 on 2020-08-16 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dav_app', '0002_onlineclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlineclass',
            old_name='date',
            new_name='c_date',
        ),
    ]
