# Generated by Django 3.0.5 on 2020-08-16 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dav_app', '0005_auto_20200816_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineclass',
            name='c_day',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='onlineclass',
            name='c_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
