# Generated by Django 3.0.5 on 2020-08-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dav_app', '0006_auto_20200816_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineclass',
            name='c_link',
            field=models.URLField(blank=True),
        ),
    ]
