# Generated by Django 3.0.5 on 2020-08-16 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dav_app', '0007_onlineclass_c_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.CharField(max_length=2)),
                ('ts_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('te_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('t_day', models.CharField(blank=True, max_length=5)),
                ('sub', models.CharField(max_length=10)),
                ('t_link', models.URLField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='onlineclass',
            old_name='c_date',
            new_name='ce_date',
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='cs_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
